name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate stats
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: PiragashSelvaratnam
          template: classic
          base: header, activity, community, repositories
          config_timezone: UTC
          config_display: large

      - name: Generate top languages
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: PiragashSelvaratnam
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          config_timezone: UTC
